name: tag

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
